on:
  pull_request:
    branches: main
name: build
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -o backend-service
      - name: create environment variables
        run: |
          echo "LOGIN_TEST_USER_ID=${{ secrets.LOGIN_TEST_USER_ID }}" >> $GITHUB_ENV
          echo "LOGIN_TEST_USER_PASS=${{ secrets.LOGIN_TEST_USER_PASS }}" >> $GITHUB_ENV
          touch .env
          echo "${{ secrets.DB_USER_NAME }}" >> .env
          echo "${{ secrets.DB_PASS }}" >> .env
          echo "${{ secrets.DB_HOST }}" >> .env
          echo "${{ secrets.DB_PORT }}" >> .env
          echo "${{ secrets.DB_NAME }}" >> .env
          echo "${{ secrets.SIGN_KEY }}" >> .env
      - name: run test
        run: go test
