name: Manual Deployment
on: 
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false
jobs:
  deploy:
    name: Deploy to Digital Ocean
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.CHAT_BACKEND_HOST }}
      USER: ${{ secrets.CHAT_BACKEND_HOST_USER }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build
      - name: deploy
        run: |
          touch .env
          echo "${{ secrets.DB_USER_NAME }}" >> .env
          echo "${{ secrets.DB_PASS }}" >> .env
          echo "${{ secrets.DB_HOST }}" >> .env
          echo "${{ secrets.DB_PORT }}" >> .env
          echo "${{ secrets.DB_NAME }}" >> .env
          echo "${{ secrets.DB_SIGN_KEY }}" >> .env
          echo "${{ secrets.CHAT_DOMAIN }}" >> .env
          echo "${{ secrets.WS_DOMAIN }}" >> .env
          echo "${{ secrets.CHAT_BACKEND_SSH_KEY }}" > ssh-key.pem
          chmod 600 ./ssh-key.pem
          eval $(ssh-agent)
          ssh-add ./ssh-key.pem
          ssh -o StrictHostKeyChecking=no "$USER"@"$HOST" systemctl stop chat-backend
          scp -o StrictHostKeyChecking=no ./chat-backend "$USER"@"$HOST":/root/chat-backend
          scp -o StrictHostKeyChecking=no ./.env "$USER"@"$HOST":/root/chat-backend
          ssh -o StrictHostKeyChecking=no "$USER"@"$HOST" systemctl restart chat-backend
